window: "5min"

# 보간(interpolation) : 관측된 점들 사이의 값을, 간단한 함수(선형·스플라인 등)로 추정해 채우는 것 (범위 밖은 외삽)
# 결측 대치(imputation) : 이전/다음 값 복사 단순 대치(imputation)

# 0) RAW 단계 이상치 처리
pre:
  bounds:                       # 컬럼별 허용범위
    outdoor_temp:               {min: -30, max: 50}
    wind_direction:             {min: 0,   max: 360}
    wind_speed:                 {min: 0,   max: 100}
    rain_sensor:                {min: 0,   max: 1}
    outdoor_solar:              {min: 0,   max: 2000}
    cumulative_solar_outdoor:   {min: 0,   max: 5000}
    indoor_temp_1:              {min: -10, max: 50}
    indoor_temp_2:              {min: -10, max: 50}
    avg_indoor_temp:            {min: -10, max: 50}
    indoor_humidity_1:          {min: 0,   max: 100}
    indoor_humidity_2:          {min: 0,   max: 100}
    avg_indoor_humidity:        {min: 0,   max: 100}
    co2_concentration_1:        {min: 0,   max: 5000}
    supply_temp_1:              {min: -10, max: 100}
    supply_temp_2:              {min: -10, max: 100}
    return_temp_1:              {min: -10, max: 100}
    return_temp_2:              {min: -10, max: 100}
    moisture_deficit:           {min: 0,   max: 50}
    saturated_moisture:         {min: 0,   max: 100}
    absolute_humidity:          {min: 0,   max: 100}
    dew_point:                  {min: -30, max: 50}
    skylight_opening_left:      {min: 0,   max: 100}
    skylight_opening_right:     {min: 0,   max: 100}
    hvac_outer_window_opening_left:  {min: 0, max: 100}
    hvac_outer_window_opening_right: {min: 0, max: 100}
    hvac_inner_window_opening_left:  {min: 0, max: 100}
    hvac_inner_window_opening_right: {min: 0, max: 100}
    side_opening_1_left:        {min: 0,   max: 100}
    side_opening_1_right:       {min: 0,   max: 100}
    side_opening_2_left:        {min: 0,   max: 100}
    side_opening_2_right:       {min: 0,   max: 100}
    horizontal_curtain_1_opening: {min: 0, max: 100}
    horizontal_curtain_2_opening: {min: 0, max: 100}
    side_1_opening:             {min: 0,   max: 100}
    side_2_opening:             {min: 0,   max: 100}
    external_shade_opening:     {min: 0,   max: 100}
    fcu_opening:                {min: 0,   max: 100}
    tube_rail_opening:          {min: 0,   max: 100}
  bounds_mode: "nan"         # "nan"(범위 밖→NaN) | "clip"(경계로 자름)
  impute:
    strategy: "ffill_then_bfill"  # "ffill" | "bfill" | "ffill_then_bfill"
    limit: 5  # 분 단위 한계(±K분)
    day_fallback_days: [1,2,3]      # 1 == 전일, 2 == 2일전, ...
    day_tolerance_min: 0        # 전일 같은 시각 정확히(±0분)
    by: null                 # 그룹키 있으면 예: "device_id"
    order_col: "timestamp"

# 1) 값 변환 (열별 매핑)
value_map:
  circulation_fan_status: {201: 1, 0: 0}
  fcu_status: {201: 1, 0: 0}
  fog_status: {201: 1, 0: 0}
  fcu_circulation_status: {201: 1, 0: 0}
  tube_rail_circulation_status: {201: 1, 0: 0}
  hvac_unit_3_status: {201: 1, 0: 0}
  hvac_unit_4_status: {201: 1, 0: 0}
  hvac_unit_5_status: {201: 1, 0: 0}
  circulation_pump_1_status: {201: 1, 0: 0}
  circulation_pump_2_status: {201: 1, 0: 0}
  co2_system_status: {201: 1, 0: 0}
  lighting_status: {201: 1, 0: 0}

# 2) 집계 대상
x_mean_cols:            # 5분 평균
  - outdoor_temp
  - wind_direction
  - wind_speed
  - outdoor_solar
  - cumulative_solar_outdoor
  - indoor_temp_1
  - indoor_temp_2
  - avg_indoor_temp
  - indoor_humidity_1
  - indoor_humidity_2
  - avg_indoor_humidity
  - co2_concentration_1
  - supply_temp_1
  - supply_temp_2
  - return_temp_1
  - return_temp_2
  - moisture_deficit
  - saturated_moisture
  - absolute_humidity
  - dew_point
  - skylight_opening_left
  - skylight_opening_right
  - hvac_outer_window_opening_left
  - hvac_outer_window_opening_right
  - hvac_inner_window_opening_left
  - hvac_inner_window_opening_right
  - side_opening_1_left
  - side_opening_1_right
  - side_opening_2_left
  - side_opening_2_right
  - horizontal_curtain_1_opening
  - horizontal_curtain_2_opening
  - side_1_opening
  - side_2_opening
  - external_shade_opening
  - fcu_opening
  - tube_rail_opening

x_sum_cols:             # 5분 누적 합
  - rain_sensor
  - circulation_fan_status
  - fcu_status
  - fog_status
  - fcu_circulation_status
  - tube_rail_circulation_status
  - hvac_unit_3_status
  - hvac_unit_4_status
  - hvac_unit_5_status
  - circulation_pump_1_status
  - circulation_pump_2_status
  - co2_system_status
  - lighting_status